spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi
    username: suraj
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update